"""The fabrication marker, end to end from contract to agent.

`metadata._simulated` is what stops Localize ranking cells over a dice roll (CLAUDE.md rule 13)
and what makes the dashboard's Simulated badge honest. Both halves broke silently once already:
the marker existed but the simulate console supplied its own geo, so eventTracker read "the caller
supplied the key" as "a real signal supplied it" and marked nothing.
"""
import api.main as main
from api.intelligence.contracts import load_declared
from api.intelligence.tools import _unsliceable_reason


def _declared():
    return load_declared()


def test_provenance_reports_every_dimension_a_contract_calls_fabricated():
    """The endpoint's allowlist must cover what the contracts actually flag.

    A contract that declares a new `live_fabricated` dimension and an endpoint that does not
    report it produces an unbadged chart over generated data -- the exact silent failure the
    marker exists to prevent.
    """
    flagged = set()
    for contract in _declared().values():
        flagged |= contract.fabricated_dimensions()
    missing = sorted(flagged - set(main.PROVENANCE_DIMENSIONS))
    assert not missing, (
        "contracts flag these as fabricated but /metrics/dimension_provenance does not report "
        "them, so a chart built on one carries no badge: %s" % missing)


def test_response_time_is_reported_even_though_no_contract_declares_it():
    """It is not a contract dimension, it is a KPI card. Both need the same marker."""
    assert "response_time_ms" in main.PROVENANCE_DIMENSIONS


def test_agent_states_why_it_refused_when_every_dimension_is_fabricated():
    """"No segment was localized" reads as "we looked and found nothing"."""
    reason = _unsliceable_reason("kyc_completion_rate")
    assert reason, "a fully-fabricated contract must explain itself"
    assert "generated by the producer" in reason
    for dim in ("device_type", "location", "continent"):
        assert dim in reason, "the reason names which dimensions were refused"


def test_agent_stays_silent_when_a_real_dimension_exists():
    """pro_revenue can slice event_name, so an empty result really does mean 'found nothing'."""
    assert _unsliceable_reason("pro_revenue") == ""


def test_agent_stays_silent_for_fact_based_contracts():
    """Retail dimensions are columns on a fact table -- measured, never synthesised."""
    for kpi in ("net_deposit_growth", "fee_revenue"):
        assert _unsliceable_reason(kpi) == "", kpi


def test_unknown_or_empty_kpi_never_raises():
    assert _unsliceable_reason("") == ""
    assert _unsliceable_reason("no_such_kpi") == ""
