"""Dashboard cosmetics only: taxonomy page -> frontend URL, and canonical event ->
human label. The ONE canonicalisation vocabulary now lives in pipeline/taxonomy/
(plan Phase 3/5). Nothing here parses or resolves an event name.
"""
from __future__ import annotations

URL_MAP: dict[str, str] = {'accounts': '/accounts',
 'admin_feature_toggles': '/admin/feature-toggles',
 'admin_loans': '/admin/loans',
 'admin_simulate': '/admin/simulate',
 'approvals': '/approvals',
 'auth': '/login',
 'cards': '/cards',
 'dashboard': '/dashboard',
 'loans': '/loans',
 'login': '/login',
 'payees': '/payees',
 'payment': '/transactions',
 'payments': '/transactions',
 'profile': '/profile',
 'register': '/register',
 'transactions': '/transactions',
 'transfers': '/transfers'}

FEATURE_DISPLAY_NAMES: dict[str, str] = {'account.page.view': 'Accounts View',
 'accounts.open_account.failed': 'Account Open Failed',
 'accounts.open_account.success': 'Account Opened',
 'accounts.page.view': 'Accounts View',
 'accounts.transfer_money.error': 'Transfer Error',
 'accounts.transfer_money.failed': 'Transfer Failed',
 'accounts.transfer_money.success': 'Transfer Success',
 'admin_feature_toggles.page.view': 'Admin Toggles View',
 'admin_feature_toggles.toggle_feature.failed': 'Feature Toggle Failed',
 'admin_feature_toggles.toggle_feature.success': 'Feature Toggled',
 'admin_loans.approve.failed': 'Loan Approve Failed',
 'admin_loans.approve.success': 'Loan Approved',
 'admin_loans.page.view': 'Admin Loans View',
 'admin_loans.reject.failed': 'Loan Reject Failed',
 'admin_loans.reject.success': 'Loan Rejected',
 'admin_loans.view_details.view': 'Admin Loan Details',
 'admin_simulate.page.view': 'Admin Simulator View',
 'admin_simulate.run_simulation.failed': 'Simulation Failed',
 'admin_simulate.run_simulation.success': 'Simulation Run',
 'ai-insights.book.access': 'AI Insights Book Access',
 'ai-insights.book.failure': 'AI Insights Book Access Failed',
 'ai-insights.book.success': 'AI Insights Book Access',
 'ai-insights.page.view': 'AI Insights View',
 'ai-insights.stats.view': 'AI Insights Stats View',
 'auth.role.violation': 'Role Violation',
 'bulk-payroll-processing.batch.failure': 'Bulk Payroll Failed',
 'bulk-payroll-processing.batch.success': 'Bulk Payroll Success',
 'bulk-payroll-processing.page.view': 'Bulk Payroll View',
 'bulk-payroll-processing.payees.view': 'Payroll Payee List',
 'bulk-payroll-processing.search.failure': 'Payroll Search Failed',
 'bulk-payroll-processing.search.success': 'Payroll Search',
 'crypto-trading.page.view': 'Crypto Trading View',
 'crypto-trading.portfolio.view': 'Crypto Portfolio View',
 'crypto-trading.price_feeds.failure': 'Crypto Price Feeds Failed',
 'crypto-trading.price_feeds.view': 'Crypto Price Feeds View',
 'crypto-trading.trade_execution.failure': 'Crypto Trade Execution Failed',
 'crypto-trading.trade_execution.success': 'Crypto Trade Execution',
 'dashboard.analytics_tab.error': 'Dashboard Analytics Error',
 'dashboard.analytics_tab.view': 'Dashboard Analytics',
 'dashboard.feature.usage': 'Feature Usage',
 'dashboard.feature.view': 'Feature View',
 'dashboard.location.captured': 'Location Captured',
 'dashboard.overview.error': 'Dashboard Overview Error',
 'dashboard.overview.view': 'Dashboard Overview',
 'dashboard.page.view': 'Dashboard View',
 'loan.applied.success': 'Loan App Submitted',
 'loan.approved.success': 'Loan Approved',
 'loan.kyc_abandoned.failure': 'Loan KYC Abandoned',
 'loan.kyc_completed.success': 'Loan KYC Completed',
 'loan.kyc_failed.failure': 'Loan KYC Failed',
 'loan.kyc_started.success': 'Loan KYC Started',
 'loan.page.view': 'Loans View',
 'loans.apply_loan.action': 'Loan Flow Started',
 'loans.emi_estimator.action': 'EMI Calculated',
 'loans.kyc.abandoned': 'Loan KYC Abandoned',
 'loans.kyc.failed': 'Loan KYC Failed',
 'loans.kyc.success': 'Loan KYC Completed',
 'loans.page.view': 'Loans View',
 'loans.proceed_to_kyc.action': 'Loan KYC Started',
 'loans.proceed_to_kyc.failed': 'Loan KYC Start Failed',
 'loans.submit_application.error': 'Loan App Error',
 'loans.submit_application.failed': 'Loan App Failed',
 'loans.submit_application.success': 'Loan App Submitted',
 'login.auth.error': 'Login Error',
 'login.auth.failed': 'Login Failed',
 'login.auth.success': 'Login Success',
 'login.page.view': 'Login Page',
 'payee.add_payee.failure': 'Payee Add Failed',
 'payee.add_payee.success': 'Payee Added',
 'payee.add_payee.view': 'Payee Add Viewed',
 'payee.copy_account_number.failure': 'Account Copy Failed',
 'payee.copy_account_number.success': 'Account Copied',
 'payee.edit_payee.failure': 'Payee Edit Failed',
 'payee.edit_payee.success': 'Payee Edited',
 'payee.page.view': 'Payees View',
 'payee.pay_now.failure': 'Payment Failed',
 'payee.pay_now.success': 'Payment Success',
 'payee.remove_payee.failure': 'Payee Remove Failed',
 'payee.remove_payee.success': 'Payee Removed',
 'payee.search_payee.failure': 'Payee Search Failed',
 'payee.search_payee.success': 'Payee Searched',
 'payees.add_payee.failed': 'Payee Add Failed',
 'payees.add_payee.success': 'Payee Added',
 'payees.add_payee.view': 'Payee Add Viewed',
 'payees.copy_account_number.failed': 'Account Copy Failed',
 'payees.copy_account_number.success': 'Account Copied',
 'payees.edit_payee.failed': 'Payee Edit Failed',
 'payees.edit_payee.success': 'Payee Edited',
 'payees.page.view': 'Payees View',
 'payees.pay_now.failed': 'Payment Failed',
 'payees.pay_now.success': 'Payment Success',
 'payees.remove_payee.failed': 'Payee Remove Failed',
 'payees.remove_payee.success': 'Payee Removed',
 'payees.search_payee.failed': 'Payee Search Failed',
 'payees.search_payee.success': 'Payee Searched',
 'pro-feature.ai-insights.read_online': 'AI Insights Read',
 'pro-feature.ai-insights.read_online.failed': 'AI Insights Read Failed',
 'pro-feature.bulk-payroll-processing.add_payee': 'Payroll Payee Added',
 'pro-feature.bulk-payroll-processing.add_payee.failed': 'Payroll Payee Add Failed',
 'pro-feature.bulk-payroll-processing.page_view': 'Bulk Payroll View',
 'pro-feature.bulk-payroll-processing.pay_all_failed': 'Bulk Payroll Failed',
 'pro-feature.bulk-payroll-processing.pay_all_success': 'Bulk Payroll Success',
 'pro-feature.bulk-payroll-processing.search_by_name': 'Payroll Searched',
 'pro-feature.bulk-payroll-processing.search_by_name.failed': 'Payroll Search Failed',
 'pro-feature.crypto-trading.buy_failed': 'Crypto Buy Failed',
 'pro-feature.crypto-trading.buy_success': 'Crypto Bought',
 'pro-feature.crypto-trading.page_view': 'Crypto Trading View',
 'pro-feature.crypto-trading.sell_failed': 'Crypto Sell Failed',
 'pro-feature.crypto-trading.sell_success': 'Crypto Sold',
 'pro-feature.page.view': 'Pro Features View',
 'pro-feature.wealth-management-pro.insights_view': 'Wealth Insights',
 'pro-feature.wealth-management-pro.insights_view.error': 'Wealth Insights Error',
 'pro-feature.wealth-management-pro.insights_view.failed': 'Wealth Insights Failed',
 'pro-feature.wealth-management-pro.rebalance_failed': 'Wealth Rebalance Failed',
 'pro-feature.wealth-management-pro.rebalance_success': 'Wealth Rebalanced',
 'pro.new_feature.view': 'New Pro Feature View',
 'profile.edit_details.error': 'Profile Details Edit Error',
 'profile.edit_details.failed': 'Profile Details Edit Failed',
 'profile.edit_details.success': 'Profile Details Edited',
 'profile.page.view': 'Profile View',
 'profile.view': 'Profile View',
 'register.auth.error': 'Register Error',
 'register.auth.failed': 'Register Failed',
 'register.auth.success': 'Register Success',
 'register.page.view': 'Register Page',
 'transaction.filter_by_date.failure': 'Transactions Filter Failed',
 'transaction.filter_by_date.success': 'Transactions Filtered',
 'transaction.history.view': 'Transaction History Viewed',
 'transaction.page.view': 'Transactions View',
 'transaction.pay_now.failure': 'Payment Failed',
 'transaction.pay_now.success': 'Payment Success',
 'transaction.search_transactions.failure': 'Transaction Search Failed',
 'transaction.search_transactions.success': 'Transaction Searched',
 'transaction.transfer.failure': 'Transfer Failed',
 'transaction.transfer.success': 'Transfer Success',
 'transactions.filter_by_date.failed': 'Transactions Filter Failed',
 'transactions.filter_by_date.success': 'Transactions Filtered',
 'transactions.history.view': 'Transaction History Viewed',
 'transactions.page.view': 'Transactions View',
 'transactions.pay_now.failed': 'Payment Failed',
 'transactions.pay_now.success': 'Payment Success',
 'transactions.search_transactions.failed': 'Transaction Search Failed',
 'transactions.search_transactions.success': 'Transaction Searched',
 'wealth-management-pro.insights.failure': 'Wealth Insights Failed',
 'wealth-management-pro.insights.view': 'Wealth Insights',
 'wealth-management-pro.page.view': 'Wealth Management View',
 'wealth-management-pro.rebalance.failure': 'Wealth Rebalance Failed',
 'wealth-management-pro.rebalance.success': 'Wealth Rebalanced'}

def resolve_display_name(event_name: str) -> str:
    return FEATURE_DISPLAY_NAMES.get(event_name, event_name)

def resolve_url(page: str) -> str:
    return URL_MAP.get(page, "/")
